image: node:14.16.0

stages:
  - build
  - test

cache: &global_cache # per-branch cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
  # make push explicit
  policy: pull

build:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    # prepare script is skipped by install/ci when running NPM 6 as root.
    # This line can be safely removed with NPM 7+ (see NPM Changelog)
    - npm run prepare
    # Build demo application
    # Still some ESlint warnings to be fixed: disable ESlint at this stage
    - DISABLE_ESLINT_PLUGIN=true npm run build
  artifacts:
    paths:
      - node_modules/
      - build/
    expire_in: 3 days
  cache:
    <<: *global_cache
    policy: pull-push

test:
  stage: test
  variables:
    COUCHDB_HOST: couchdb
    COUCHDB_PORT: 5984
    COUCHDB_URL: http://$COUCHDB_HOST:$COUCHDB_PORT/
    COUCHDB_USER: admin
    COUCHDB_PASSWORD: "admin"
    DBNAME: testdb

  services:
    - couchdb:latest

  before_script:
    - curl -u "$COUCHDB_USER:$COUCHDB_PASSWORD"
      -X PUT $COUCHDB_URL/_users
    - curl -u "$COUCHDB_USER:$COUCHDB_PASSWORD"
      -X PUT $COUCHDB_URL/$DBNAME

  script:
    - npm test

  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/


test:
  stage: test
  # node 15+ has bug #2143 : https://github.com/npm/cli/issues/2143
  image: node:14.16.0
  variables:
    COUCHDB_HOST: couchdb
    COUCHDB_PORT: 5984
    COUCHDB_URL: http://$COUCHDB_HOST:$COUCHDB_PORT/
    COUCHDB_USER: admin
    COUCHDB_PASSWORD: "admin"

  services:
    - couchdb:latest

  before_script:
    # Gradle in APT repository is outdated:
    #   install dependencies and download Gradle 6.8.3
    - apt-get update &&
      apt-get install -y default-jdk-headless
    - wget -q "https://services.gradle.org/distributions/gradle-6.8.3-bin.zip"
    - unzip -q gradle-6.8.3-bin.zip
    - PATH=$(readlink -e gradle-6.8.3/bin):$PATH
    # setup couchdb
    - curl -su "$COUCHDB_USER:$COUCHDB_PASSWORD"
      -X PUT $COUCHDB_URL/_users
    # install c-service
    - npm config set @concordant:registry "https://gitlab.inria.fr/api/v4/packages/npm/"
    - npm config set '//gitlab.inria.fr/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    # install in foreground, run in background
    - npm install @concordant/c-service
    - npx @concordant/c-service &

  script:
    - gradle check
  artifacts:
    paths:
      - build/reports/
    when: always
